# Generated by Django 3.2.7 on 2021-09-10 06:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'college_address',
            },
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('year_of_completion', models.IntegerField()),
                ('college_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collegeaddres')),
            ],
            options={
                'db_table': 'education_detail',
            },
        ),
        migrations.CreateModel(
            name='FamilyAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=30)),
                ('address_line2', models.CharField(blank=True, max_length=30)),
                ('landmark', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'family_address',
            },
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=30)),
                ('years_of_experience', models.IntegerField()),
                ('company_name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'job_detail',
            },
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=30)),
                ('address_line2', models.CharField(blank=True, max_length=30)),
                ('landmark', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'job_location',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_Of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('aadhar_card', models.CharField(max_length=50)),
                ('pan_card', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familyaddres')),
                ('education_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.educationdetail')),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobdetail')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.joblocation'),
        ),
    ]
