# Generated by Django 3.2.7 on 2021-09-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollegeAddres',
            new_name='CollegeAddress',
        ),
        migrations.RenameModel(
            old_name='FamilyAddres',
            new_name='FamilyAddress',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='date_Of_birth',
            new_name='date_of_birth',
        ),
    ]
